spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: dev  #开发环境
  application:
    name: spring-cloud-config-dev
server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
      
---

spring:
  profiles: test  #测试环境
  application:
    name: spring-cloud-config-test
